services:
  db:
    container_name: postgres-db
    image: postgres:16.4
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: always
    networks:
      - back_net
    volumes:
      - .postgres:/posgtres
      - randomizer_vol:/var/lib/postgresql/data
  web:
    build:
      context: ./randomizer_private
      dockerfile: Dockerfile
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_HOST
    command: bash -c "rm -f tmp/pids/server.pid && bundle install && bundle exec rails s -b 0.0.0.0"
    volumes:
      - .:/rails
      - rails_assets:/rails/public/assets
    networks:
      - back_net
    depends_on:
      - db
    secrets:
      - source: rails_env
        target: /rails/.env
      - source: rails_product_key
        target: /rails/config/credentials/production.key
    tty: true
    stdin_open: true
  nginx:
    build: ./nginx/
    ports:
      - "80:80"
      - "443:443"
    networks:
      - default
      - back_net
    depends_on:
      - db
    secrets:
      - source: nginx_key_pem_secret
        target: /etc/nginx/ssl/nginx-key.pem
      - source: nginx_pem_secret
        target: /etc/nginx/ssl/nginx.pem
      - source: nginx_origin_ca
        target: /etc/nginx/ssl/origin_ca_ecc_root.pem

volumes:
  randomizer_vol:
  rails_assets:
  https-portal-data:
networks:
  back_net:
secrets:
  nginx_origin_ca:
    file: ./secrets/origin_ca_ecc_root.pem
  nginx_key_pem_secret:
    file: ./secrets/nginx-key.pem
  nginx_pem_secret:
    file: ./secrets/nginx.pem
  rails_env:
    file: ./secrets/.env
  rails_product_key:
    file: ./secrets/production.key
