volumes:
  randomizer_vol:
  https-portal-data:
networks:
  back_net:
secrets:
  nginx_key_pem_secret:
    file: ./secrets/nginx-key.pem
  nginx_pem_secret:
    file: ./secrets/nginx.pem

services:
  db:
    container_name: postgres-db
    image: postgres:16.4
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: always
    networks:
      - back_net
    volumes:
      - .postgres:/posgtres
      - randomizer_vol:/var/lib/postgresql/data
    ports:
      - 5433:5432
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_HOST
    command: bash -c "rm -f tmp/pids/server.pid && bundle install && bundle exec rails s -b 0.0.0.0"
    volumes:
      - .:/rails
    networks:
      - back_net
    depends_on:
      - db
    tty: true
    stdin_open: true
  nginx:
    build: ./nginx/
    ports:
      - "80:80"
      - "443:443"
    networks:
      - default
      - back_net
    secrets:
      - nginx_key_pem_secret
      - nginx_pem_secret
