volumes:
  randomizer_vol:
networks:
  back_net:


services:
  db:
    container_name: postgres-db
    image: postgres:16.4
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: always
    networks:
      - back_net
    volumes:
      - .postgres:/posgtres
    ports:
      - 5433:5432
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_HOST
    command: bash -c "rm -f tmp/pids/server.pid && bundle install && bundle exec rails s -b 0.0.0.0"
    volumes:
      - .:/rails
    networks:
      - back_net
      - default
    ports:
      - "3000:3000"
    depends_on:
      - db
    tty: true
    stdin_open: true
